### ISSUE TITLE
*Mechanical* WebCam Cover

### ISSUE THREAD

**Issue by nelsonic** [dwyl/print-me#30]
We are all privacy-conscious @dwyl with [_good reason_](https://www.hackread.com/mark-zuckerbergs-laptop-cam-tape/) 
(_"bad people" will use your webcam if they are ever able to "own" your laptop!_)

We already have _Stickers_: https://github.com/dwyl/merchandise/issues/23 to cover our WebCams
However _sadly_ the stickers do not _stick_ to laptops with a metallic or plastic "bezel" (_only glass_)
Therefore I propose buying a **_mechanical_ webcam covers** for everyone that wants them.

## Basic Un-branded Version

https://www.alibaba.com/product-detail/Ultra-Thin-Design-Web-Camera-Cover_60706782609.html
![image](https://user-images.githubusercontent.com/194400/32419552-af8d8b22-c273-11e7-8eb0-6bdb724fb708.png)

## With Printed Logo:

https://www.alibaba.com/product-detail/OEM-logo-cheap-price-laptop-webcam_60705491576.html
![image](https://user-images.githubusercontent.com/194400/32419665-ae86dba0-c275-11e7-8874-4f3816b9b98f.png)

In the first instance we need enough for everyone @dwyl who wants one.
What would be a _sensible_ ***initial*** order? **30**?

> Note if we decide to print the @dwyl logo on, then min-order is 100.
> But I personally don't _mind_ spending a bit more if they are "branded" and you give them away to everyone you meet at conferences/meetups cause we _want_ people to associate the _product_ with being "_privacy-focussed_"

## Todo

+ [x] @iteles to Decide/confirm quantity. (_I propose 30 and see how popular they are_) ❓ 
+ [x] @iteles to Decide if we are going to _custom_ print them with the @dwyl logo on them. (_min order 100_)
+ [ ] @yvonne-liu has [kindly offered](https://github.com/dwyl/merchandise/issues/23#issuecomment-341964856) to help source them from China. 🎉

**Comment by iteles** [comment]
100 _with_ dwyl logo & brand name. As you say @nelsonic there are LOTS of people who will use these and this is a very small outlay (unlike £13 per t-shirt for example!).

Need the design too! @markwilliamfirth Do you have some design files we can already reuse for this? Maybe the heart logo with the word dwyl next to it like we have on the back of our current t-shirts (without the `io`) for example?

**Comment by yvonne-liu** [comment]
I can step in once the following is ready:

- [ ] the logo file with specific pantone colors, if applicable 
- [ ] the preferred shape (square edge or oval or it doesn't matter?) 
- [ ] the color of the webcam cover (black/white is probably the easiest/cheapest option)

**Comment by rub1e** [comment]
I've just done a bit of research to rekindle this

It's a familiar story - the more you buy the cheaper they are. To secure a good price you need to be buying min. 500

Prices vary but this is a good indication:

* 100 @ £1.75
* 250 @ £1.50
* 500 @ £1.10

Now, if we went with Alibaba we could cut that price in half, but I'm not blown away by the quality of the product (if their images are anything to go by):

![image](https://user-images.githubusercontent.com/11595920/46738490-3ddf3880-cc96-11e8-9c39-a49e41381810.png)

Also, rather cleverly, they don't display how much shipping would be - and I suspect that might be £££ from China...

So there's a couple of ways we could go about this:

* Get some unbranded samples to check quality before putting in a larger order with our logo on it
* Use a supplier that will let us order 50-100, get a smaller order, and just swallow the higher unit cost

I'm torn because spending significant money on this doesn't seem right, but OTOH there's no sense in getting cheap tat if you want to give it to clients as marketing material (and these things are REALLY suited to giving away to clients - imagine having your logo in front of your client's face for eight hours a day!!)

So... discuss...

(If you don't fancy discussing, my proposal would be that we just get 100 for £1.75 ish and be done with it)

Once we agree on indicative amounts and rough spend, I'll put some design options up - they're tonnes - rectangle, lozenge, "peekaboo"...

PS @iteles the correct technical term is indeed `(sliding) webcam cover`

**Comment by iteles** [comment]
@rub1e Not really blown away by the quality of the ones you shared either, but I think at a minimum it would be great to prep the things that @yvonne-liu mentioned in https://github.com/dwyl/print-me/issues/30#issuecomment-342113310 to get things underway!

(and thanks for the `technical term` ❤️ )
